fguilloucamargo/tennismatch

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/components/_search.scss
app/views/devise/sessions/new.html.erb
app/views/layouts/application.html.erb
app/views/shared/_navbar.html.erb

Adding navbar + container for sign/in and register

Adding navbar

---

app/models/request.rb
app/models/user.rb

Adding Active Record validations

Adding Active Record validations

---

db/migrate/20200616092902_add_photo_to_users.rb
db/schema.rb

add column photo to Users
@EdouardCouten @romaingericot @fguilloucamargo

AddPhotoToUsers

---

app/controllers/application_controller.rb
app/controllers/requests_controller.rb
app/models/user.rb
app/views/devise/registrations/new.html.erb
app/views/requests/new.html.erb

Adding mandatory inputs to simple form

---

db/migrate/20200616121430_add_location_to_requests.rb
db/schema.rb

Add location in Request model as string

Add location to request model

---

app/assets/stylesheets/components/_footer.scss
app/views/shared/_footer.html.erb
db/seeds.rb

Add requests to seed

---

app/controllers/requests_controller.rb
app/views/requests/show.html.erb
db/migrate/20200616092902_add_photo_to_users.rb

Show ok pour controller et vue 
@fguilloucamargo  @EdouardCouten @romaingericot

Requestcontroller show

---

app/views/requests/index.html.erb

Correction bug routes in request index

correction path request show

---

db/schema.rb

changing matches to matchs

---

app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_navbar.scss
app/views/requests/new.html.erb
app/views/requests/show.html.erb
app/views/shared/_footer.html.erb
app/views/shared/_navbar.html.erb

Responsive, links routes and colors

Nav and footer corrections

---

app/controllers/matches_controller.rb
app/models/match.rb
db/migrate/20200617101047_create_matches.rb
db/schema.rb
db/seeds.rb

Change teh controller and db names and add some matches to seed

Matches problem

---

app/controllers/matchs_controller.rb
app/views/layouts/application.html.erb
app/views/shared/_flashes.html.erb

Devise alerts

---

app/controllers/matchs_controller.rb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/new.html.erb

Devise containers

---

app/controllers/matches_controller.rb
app/controllers/matchs_controller.rb
app/controllers/requests_controller.rb
app/models/request.rb
app/models/user.rb
app/views/matches/show.html.erb
app/views/requests/show.html.erb
config/routes.rb

Add view and controller of match

Match controller and view

---

app/views/requests/index.html.erb

Changing path for show

---

db/seeds.rb

New seed with better quality photo and 10 shuffle requests

New seed and best quality photo

---

app/views/matches/index.html.erb

Hotfix dashboard

---

app/views/requests/index.html.erb

Add font awesome icons to home cards

Hotfix cards icons

---

app/controllers/matches_controller.rb
app/views/requests/index.html.erb

I have add a if condition in the request#index to show only the request that are still available

request index shows only request available

---

Gemfile
Gemfile.lock
app/controllers/requests_controller.rb
app/models/request.rb
app/views/requests/index.html.erb

Add the search bar and the pg search

Search bar

---

app/controllers/requests_controller.rb
app/views/requests/index.html.erb
app/views/requests/new.html.erb

Some changes in the layout in new and fix bug redirect in the request new

Layout improve

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_profile.scss
app/views/requests/index.html.erb
app/views/requests/show.html.erb

Resquest btn

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_match.scss
app/views/matches/index.html.erb

Changing match index and resize card class

view match and size card

---

app/views/matches/index.html.erb
app/views/requests/show.html.erb
config/environments/production.rb

bug photo cloudinary + env prod

Photos bug

---

app/views/requests/index.html.erb

it's not a test, true code

---

app/views/requests/index.html.erb

Please review my code @fguilloucamargo @DGDGboy @EdouardCouten

Correcting Heroku log error

---

app/views/matches/index.html.erb

New message when no match to come

Add a new message when no match
